resources:
  repositories:
    - repository: templates # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#repository-resource
      type: github
      name: rdbartram/PSBuildRelease
      ref: refs/heads/master
      endpoint: github

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - releases/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop

jobs:
  - template: Yaml Build Defintions/ModuleTestIncPublish.yml@templates # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job-templates
    parameters:
      baseRepoId: oechiih/PSTello     # ID of the repo targeted by the build definition
      baseBuildDefinitionId: 3
      coverageThreshold: 1     # Minimum Pester Coverage
