# MKDocs configuration file
# reference: https://www.mkdocs.org/user-guide/configuration/
site_name: PSTello
repo_url: https://github.com/oechiih/PSTello
theme:
    name: 'material'
    palette:
      primary: 'indigo'
      accent: 'orange'
    logo: 'images/dftai.png'
markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
